version: "3.8"

services:
  go_gin:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release
    ports:
      - "3001:8081"
    networks:
      - my_app
networks:
  my_app:
    driver: bridge